"""Generate the HTCondor submit file for the WW NLL-template regeneration.

Mirrors the whizard/submit.py style. Fans out one job per
(tag, BEC-shift) pair — 5 tags × 5 shifts = 25 jobs.

Usage:
    python3 condor/ww_templates/submit.py            # writes templates.sub
    condor_submit condor/ww_templates/templates.sub

Each job runs ``compute_xsec_ww.py --only-tag <tag> --only-bec-shift <shift>``
on the worker with ``request_cpus = 4`` and ``WW_ISR_NJOBS = 4`` (set by
job.sh). One template ≈ 150 s wall.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from anywhere by adding the repo root to sys.path.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from cards import ww_default as card
from framework.common.parameters import Parameters


REPO       = Path("/afs/cern.ch/work/m/mdefranc/private/FCC/QQbar_threshold/WW_threshold")
CONDOR_DIR = REPO / "condor" / "ww_templates"
LOGS_DIR   = CONDOR_DIR / "logs"
JOB_SH     = CONDOR_DIR / "job.sh"
SUB_PATH   = CONDOR_DIR / "templates.sub"

# BEC shifts in MeV: 0 (the nominal set, no BEC subdir) plus the per-card
# step ±INPUT_VAR["BEC"] (production fit only consumes scan_{p,m}{step}).
_BEC_STEP = float(card.INPUT_VAR["BEC"])
BEC_SHIFTS_MEV = [0.0, +_BEC_STEP, -_BEC_STEP]


def _bec_label(shift: float) -> str:
    if shift == 0.0:
        return "nom"
    sign = "p" if shift > 0 else "m"
    return f"bec{sign}{abs(int(round(shift)))}"


def main() -> None:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    params = Parameters(card.PARAMETERS, scale_vars=[])
    tags = params.tags

    lines: list[str] = [
        "# Auto-generated by condor/ww_templates/submit.py — DO NOT EDIT.",
        "universe   = vanilla",
        f"executable = {JOB_SH}",
        "",
        "should_transfer_files   = NO",
        "getenv                  = false",
        '# Worker needs CVMFS + AFS visibility.',
        'requirements            = (OpSysAndVer == "AlmaLinux9" || '
        'OpSysAndVer == "CentOS9" || OpSysAndVer == "RedHat9")',
        "",
        "# Forward Kerberos so the wrapper can write back to AFS.",
        "MY.SendCredential = true",
        "",
        "request_cpus   = 4",
        "request_memory = 4096",
        "request_disk   = 1024",
        "",
        '# microcentury (1h) is enough — each template ≈ 150 s at n_jobs=4.',
        '+JobFlavour = "microcentury"',
        "",
    ]

    n = 0
    for tag in tags:
        for shift in BEC_SHIFTS_MEV:
            label = f"{tag}_{_bec_label(shift)}"
            lines += [
                f"arguments = {tag} {shift:.1f}",
                f"output  = {LOGS_DIR}/{label}.out",
                f"error   = {LOGS_DIR}/{label}.err",
                f"log     = {LOGS_DIR}/{label}.log",
                "queue 1",
                "",
            ]
            n += 1

    SUB_PATH.write_text("\n".join(lines))
    print(f"Wrote {n} job blocks to {SUB_PATH}")
    print(f"Submit with:  condor_submit {SUB_PATH}")


if __name__ == "__main__":
    main()
