#!/usr/bin/env python3
"""Resubmit the *missing* pure-WW grid points (gap-fill).

Diffs the expected (scheme, channel, varpoint, √s) lattice against the result
CSVs on EOS and writes one ``points_gap_<scheme>.txt`` + ``grid_gap_<scheme>.sub``
per scheme that has holes.  The refilled jobs reuse ``job.sh`` verbatim, so the
seed (keyed on channel,√s — not varpoint/scheme) and event count match the
original campaign and the correlated-seed de-noising still cancels.

  python3 scripts/indep_mocanlo/resubmit_gaps.py            # generate + print
  condor_submit scripts/indep_mocanlo/grid_gap_<scheme>.sub # submit each
"""
from __future__ import annotations

import argparse
import os
import sys

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from framework.process.ww.indep.grid import ecm_grid
from framework.process.ww.indep.partonic_grid import DEFAULT_RESULTS_DIR

HERE = os.path.dirname(os.path.abspath(__file__))
LOGDIR = os.path.join(HERE, "logs")

# Pure-WW assembly uses exactly these 3 stable channels (no forward-e, no ℓℓ pole).
CHANNELS = ("lnuqq", "qqqq", "mutau")

SUB_TEMPLATE = """# Auto-generated by resubmit_gaps.py — DO NOT EDIT.  Gap-fill for scheme={scheme}.
universe   = vanilla
executable = {here}/job.sh

should_transfer_files = NO
getenv                = false
requirements          = (OpSysAndVer == "AlmaLinux9" || OpSysAndVer == "CentOS9" || OpSysAndVer == "RedHat9")
MY.SendCredential     = true

request_cpus   = 1
request_memory = 3072
request_disk   = 2048
+JobFlavour    = "{flavour}"

arguments = $(channel) $(varpoint) $(ecm) 1.0 {events} {scheme} none none none
output = {logdir}/$(channel)_$(varpoint)_$(ecm)_{scheme}.out
error  = {logdir}/$(channel)_$(varpoint)_$(ecm)_{scheme}.err
log    = {logdir}/$(channel)_$(varpoint)_$(ecm)_{scheme}.log

queue channel,varpoint,ecm from {points}
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--schemes", default="gf,alpha0,alphaz")
    ap.add_argument("--events", type=int, default=500000)
    ap.add_argument("--flavour", default="tomorrow")
    ap.add_argument("--results-dir", default=DEFAULT_RESULTS_DIR,
                    help="EOS dir holding the landed *_<scheme>.csv (default: load_grids default)")
    args = ap.parse_args(argv)

    from framework.process.ww.indep.varpoints import VARPOINTS_BY_KEY
    vps = sorted(VARPOINTS_BY_KEY)
    grid = [f"{float(e):.4f}" for e in ecm_grid()]
    os.makedirs(LOGDIR, exist_ok=True)

    have = set(os.listdir(args.results_dir))   # one stat of EOS, then membership tests
    total_missing = 0
    for scheme in args.schemes.split(","):
        missing = [(ch, vp, e)
                   for ch in CHANNELS for vp in vps for e in grid
                   if f"{ch}_{vp}_ecm{e}_{scheme}.csv" not in have]
        if not missing:
            print(f"  {scheme:8s}: complete (0 missing)")
            continue
        pts = os.path.join(HERE, f"points_gap_{scheme}.txt")
        with open(pts, "w") as fh:
            for ch, vp, e in missing:
                fh.write(f"{ch} {vp} {e}\n")
        sub = os.path.join(HERE, f"grid_gap_{scheme}.sub")
        with open(sub, "w") as fh:
            fh.write(SUB_TEMPLATE.format(here=HERE, logdir=LOGDIR, points=pts,
                                         flavour=args.flavour, events=args.events,
                                         scheme=scheme))
        total_missing += len(missing)
        print(f"  {scheme:8s}: {len(missing):4d} missing -> {os.path.basename(sub)}")

    print(f"total missing: {total_missing}")
    if total_missing:
        print("submit with:")
        for scheme in args.schemes.split(","):
            sub = os.path.join(HERE, f"grid_gap_{scheme}.sub")
            if os.path.exists(sub):
                print(f"  condor_submit {sub}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
