#!/usr/bin/env python3
"""Generate the HTCondor submission for the independent-WW partonic grid.

Writes ``points.txt`` (one ``channel varpoint ecm`` per line) and ``grid.sub``
(queue-from-file).  One job per grid point, ``request_cpus=1`` (MoCaNLO points
are embarrassingly parallel; per-point precision replaces seed-averaging).

  python3 submit_grid.py [--scheme gf] [--precision 0.5] [--events 200000]
                         [--channels enuqq,lnuqq,...] [--varpoints nominal,...]
then:  condor_submit scripts/indep_mocanlo/grid.sub
"""
from __future__ import annotations

import argparse
import os
import sys

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from framework.process.ww.indep.grid import ecm_grid, n_points
from framework.process.ww.indep.channels import BLOCKS_BY_KEY
from framework.process.ww.indep.varpoints import VARPOINTS_BY_KEY

HERE = os.path.dirname(os.path.abspath(__file__))
LOGDIR = os.path.join(HERE, "logs")

SUB_TEMPLATE = """# Auto-generated by submit_grid.py — DO NOT EDIT.
universe   = vanilla
executable = {here}/job.sh

should_transfer_files = NO
getenv                = false
requirements          = (OpSysAndVer == "AlmaLinux9" || OpSysAndVer == "CentOS9" || OpSysAndVer == "RedHat9")
MY.SendCredential     = true

request_cpus   = 1
request_memory = 3072
request_disk   = 2048
+JobFlavour    = "{flavour}"

arguments = $(channel) $(varpoint) $(ecm) {prec} {events} {scheme} {lepcut} {ptmin}
output = {logdir}/$(channel)_$(varpoint)_$(ecm){cuttag}.out
error  = {logdir}/$(channel)_$(varpoint)_$(ecm){cuttag}.err
log    = {logdir}/$(channel)_$(varpoint)_$(ecm){cuttag}.log

queue channel,varpoint,ecm from {points}
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--scheme", default="gf")
    ap.add_argument("--precision", type=float, default=0.5)
    ap.add_argument("--events", type=int, default=200000)
    ap.add_argument("--flavour", default="tomorrow",
                    help="condor JobFlavour (tomorrow=1d, workday=8h, longlunch=2h)")
    ap.add_argument("--channels", default=None,
                    help="comma list to restrict channels (default all 6)")
    ap.add_argument("--varpoints", default=None,
                    help="comma list to restrict varpoints (default all 6)")
    ap.add_argument("--lepton-cut", default="none",
                    help="fiducial |cosθ_l|<COS cut (e.g. 0.95) or 'none' (inclusive)")
    ap.add_argument("--lepton-pt-min", default="none",
                    help="fiducial charged-lepton p_T>PT GeV cut (e.g. 20) or 'none'")
    ap.add_argument("--name", default=None,
                    help="campaign name (points/sub filename stem); "
                         "default derived from cut")
    args = ap.parse_args(argv)

    chans = set(args.channels.split(",")) if args.channels else set(BLOCKS_BY_KEY)
    vps = set(args.varpoints.split(",")) if args.varpoints else set(VARPOINTS_BY_KEY)
    # Mirror run_point.py's result-CSV suffix: _cut<NN>[pt<PT>].
    cuttag = "" if args.lepton_cut == "none" else f"_cut{int(round(float(args.lepton_cut)*100))}"
    if args.lepton_pt_min != "none":
        cuttag += f"pt{int(round(float(args.lepton_pt_min)))}"
    stem = args.name or ("pureww" if args.lepton_cut == "none" else f"fid{cuttag}")

    os.makedirs(LOGDIR, exist_ok=True)
    points_path = os.path.join(HERE, f"points_{stem}.txt")
    grid = ecm_grid()
    n = 0
    with open(points_path, "w") as fh:
        for ch in sorted(chans):
            if ch not in BLOCKS_BY_KEY:
                raise SystemExit(f"unknown channel {ch!r}")
            for vp in sorted(vps):
                for ecm in grid:
                    fh.write(f"{ch} {vp} {float(ecm):.4f}\n")
                    n += 1

    sub_path = os.path.join(HERE, f"grid_{stem}.sub")
    with open(sub_path, "w") as fh:
        fh.write(SUB_TEMPLATE.format(
            here=HERE, logdir=LOGDIR, points=points_path, flavour=args.flavour,
            prec=args.precision, events=args.events, scheme=args.scheme,
            lepcut=args.lepton_cut, ptmin=args.lepton_pt_min, cuttag=cuttag))

    print(f"wrote {points_path}  ({n} points; full 6×6×33 grid = {n_points()})")
    print(f"wrote {sub_path}")
    print(f"submit with:  condor_submit {sub_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
