#!/bin/bash
# WHIZARD 3.1.5 install recipe — builds the binary used by the WW-threshold
# fit framework. Run from inside WW_threshold/whizard/; produces a whizard/
# install tree as a sibling of WW_threshold/.
#
# Run on lxplus (any node with CVMFS + libtirpc-devel installed). The actual
# WHIZARD integration / event-generation runs go to fcc-ironic-02 or -03 —
# the binary lives on AFS so both nodes consume the same install.
#
# Layout produced (sibling to WW_threshold/, NOT inside it):
#   ../whizard/
#     src/         downloaded + unpacked WHIZARD source
#     build/       out-of-tree autotools build
#     install/     --prefix; bin/whizard + omega_*.opt + share/
#     work/        Sindarin scripts and run outputs (NOT cleaned by this script)
#     bin/ocaml    shebang shim for the broken LCG ocaml REPL
#     setup.sh     sourced by anything that uses the binary
#
# Idempotent: re-running just re-runs make/install. To start fresh, delete
# the sibling whizard/src/whizard-3.1.5 and whizard/build/ first.

set -euo pipefail

VERSION=3.1.5
LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt
OCAML_REL=/cvmfs/sft.cern.ch/lcg/releases/ocaml/4.14.2-7a890/x86_64-el9-gcc13-opt

# This script lives at WW_threshold/whizard/install.sh.
# Walk up two levels to the QQbar_threshold/ root, then into the sibling whizard/.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]:-$0}" )" && pwd )"
WHIZARD_TOP="$( cd "$SCRIPT_DIR/../.." && pwd )/whizard"
SRC=$WHIZARD_TOP/src
BUILD=$WHIZARD_TOP/build
PREFIX=$WHIZARD_TOP/install
BIN=$WHIZARD_TOP/bin

mkdir -p "$SRC" "$BUILD" "$PREFIX" "$BIN" "$WHIZARD_TOP/lib" "$WHIZARD_TOP/work"

# Provide a user-owned libtirpc.so symlink — fcc-ironic-03 ships only the
# runtime .so.3, no -devel package, so O'Mega-generated ME links would fail.
[ -e "$WHIZARD_TOP/lib/libtirpc.so" ] || ln -sfn /usr/lib64/libtirpc.so.3 "$WHIZARD_TOP/lib/libtirpc.so"

# --- 1. Sanity-check the host -----------------------------------------------
[ -f "$LCG_VIEW/setup.sh" ] || { echo "ERROR: LCG view missing: $LCG_VIEW"; exit 1; }
[ -f /usr/include/tirpc/rpc/types.h ] || {
    echo "ERROR: libtirpc-devel headers missing (/usr/include/tirpc/rpc/types.h)."
    echo "       WHIZARD's mcfio contrib needs Sun-RPC headers; on RHEL9 these"
    echo "       moved out of glibc into libtirpc. Install libtirpc-devel."
    exit 1
}

# --- 2. OCaml REPL shim -----------------------------------------------------
# LCG ships ocaml (the bytecode-driven REPL) with a stale jenkins-build
# shebang; ocamlc/ocamlopt/ocamldep are real ELF binaries and unaffected,
# but WHIZARD's configure runs `ocaml -version` and that needs to work.
cat > "$BIN/ocaml" <<EOF
#!/bin/bash
# Auto-generated by install_whizard.sh — DO NOT EDIT.
exec $OCAML_REL/bin/ocamlrun $OCAML_REL/bin/ocaml "\$@"
EOF
chmod +x "$BIN/ocaml"

# --- 2b. setup.sh (sourced by users + by this script's tests) ---------------
cat > "$WHIZARD_TOP/setup.sh" <<EOF
# Auto-generated by install_whizard.sh — DO NOT EDIT.
# Source this file to pick up WHIZARD's build/runtime dependencies.
WHIZARD_TOP="\$( cd "\$( dirname "\${BASH_SOURCE[0]:-\$0}" )" && pwd )"
export WHIZARD_TOP
source $LCG_VIEW/setup.sh
export PATH="\$WHIZARD_TOP/bin:\$PATH"
if [ -d "\$WHIZARD_TOP/install/bin" ]; then
    export PATH="\$WHIZARD_TOP/install/bin:\$PATH"
    export LD_LIBRARY_PATH="\$WHIZARD_TOP/install/lib:\${LD_LIBRARY_PATH:-}"
fi
if [ -e "\$WHIZARD_TOP/lib/libtirpc.so" ]; then
    export LIBRARY_PATH="\$WHIZARD_TOP/lib:\${LIBRARY_PATH:-}"
    export LD_LIBRARY_PATH="\$WHIZARD_TOP/lib:\${LD_LIBRARY_PATH:-}"
fi
: "\${OMP_NUM_THREADS:=48}"
export OMP_NUM_THREADS
EOF

# --- 3. Download source (40 MiB) --------------------------------------------
TARBALL=$SRC/whizard-$VERSION.tar.gz
SRCDIR=$SRC/whizard-$VERSION
if [ ! -d "$SRCDIR" ]; then
    if [ ! -f "$TARBALL" ]; then
        echo "==> Downloading WHIZARD $VERSION"
        curl -fL --max-time 180 -o "$TARBALL" \
             "https://whizard.hepforge.org/downloads/?f=whizard-$VERSION.tar.gz"
    fi
    echo "==> Unpacking"
    tar -C "$SRC" -xzf "$TARBALL"
fi

# --- 4. Source LCG view + put shim first on PATH ----------------------------
# shellcheck disable=SC1091
source "$LCG_VIEW/setup.sh"
export PATH="$BIN:$PATH"

# --- 5. Configure -----------------------------------------------------------
# CPPFLAGS / LIBS wire up libtirpc for the bundled mcfio (StdHEP I/O).
# FC=gfortran picks up the LCG view's gcc 13.1 toolchain.
if [ ! -f "$BUILD/Makefile" ] || [ ! -f "$BUILD/config.status" ]; then
    echo "==> Configuring"
    cd "$BUILD"
    "$SRCDIR/configure" \
        --prefix="$PREFIX" \
        --enable-fc-openmp \
        --disable-static \
        FC=gfortran F77=gfortran \
        CPPFLAGS="-I/usr/include/tirpc" \
        LIBS="-ltirpc"
fi

# --- 6. Build + install -----------------------------------------------------
echo "==> Building (this takes ~10-20 min on lxplus with -j8)"
cd "$BUILD"
make -j"${MAKE_JOBS:-8}"
echo "==> Installing to $PREFIX"
make install

echo "=================================================================="
echo "DONE. Verify with:"
echo "  source $WHIZARD_TOP/setup.sh"
echo "  whizard --version"
echo "  cd $WHIZARD_TOP/work && whizard smoke.sin    # only on ironic"
echo "=================================================================="
